### ISSUE TITLE
PyPI abandoned project procedure

### ISSUE THREAD

**Issue by da4089** [skarim/vobject#190]
Given this repository has been unmaintained for years, and the package on PyPI will be 6 years old in July 2024, I intend to pursue the PyPI "abandoned projects" process to attempt to claim the name "vobject" for use with the fork at https://github.com/py-vobject/vobject.

There are three administrators for the PyPI project: @skarim, @wpercy, and Jeffrey Harris (the original vObject author).  I have made contact with @wpercy, but they don't feel comfortable making any changes to the administrative settings.  I have been unable to reach @skarim or Jeffrey Harris after multiple attempts.

The process for transferring a name to new administrators is documented in https://peps.python.org/pep-0541/.  I have created this issue in an attempt to make contact with the current administrators to facilitate a transfer (or resumption of their own maintenance activities).

If either of @skarim or Jeffrey Harris sees this issue, it'd be great if you could reach out to discuss this.

Thanks!

**Comment by skarim** [comment]
@da4089 i added you as a collaborator on the vobject project in pypi: https://pypi.org/project/vobject/

apologies for the radio silence here, i didn't receive the previous messages because my email was misconfigured

unfortunately, i no longer have write/admin access to this repo. i will get in touch with the new owners of eventable to see if they can transfer the repo out of this org

**Comment by da4089** [comment]
Thanks @skarim!
